ALTER TABLE PRODUCTINSTANCE DROP CONSTRAINT PRDCTNSTANCEPRDCTD
ALTER TABLE ORDER_PRODUCTINSTANCE DROP CONSTRAINT RDRPRDprdctnstncsD
ALTER TABLE ORDER_PRODUCTINSTANCE DROP CONSTRAINT RDRPRDCTNSTNCErdrD
ALTER TABLE CUSTOMER_ORDER DROP CONSTRAINT CSTOMERORDERrdrsID
ALTER TABLE CUSTOMER_ORDER DROP CONSTRAINT CSTMRORDERCstmerID
DROP TABLE ORDER
DROP TABLE CUSTOMER
DROP TABLE PRODUCT
DROP TABLE PRODUCTINSTANCE
DROP TABLE ORDER_PRODUCTINSTANCE
DROP TABLE CUSTOMER_ORDER
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
